// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'3342285e8f5a85b4afbbca23cbc2d2e0e4900f7520a9e834751e03b2a41677b8'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Barang: {
      readonly id_barang: CodecTypes['pg/int4@1']['output'];
      readonly nama_barang: CodecTypes['pg/text@1']['output'];
      readonly harga: CodecTypes['pg/int4@1']['output'];
      readonly harga_beli: CodecTypes['pg/int4@1']['output'];
      readonly komisi_penjualan: CodecTypes['pg/int4@1']['output'];
    };
    readonly Klien: {
      readonly id_klien: CodecTypes['pg/int4@1']['output'];
      readonly nama: CodecTypes['pg/text@1']['output'];
      readonly alamat: CodecTypes['pg/text@1']['output'] | null;
      readonly kontak: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly KomisiLog: {
      readonly id_log: CodecTypes['pg/int4@1']['output'];
      readonly jenis_komisi: CodecTypes['pg/text@1']['output'];
      readonly nominal_masuk: CodecTypes['pg/int4@1']['output'];
      readonly id_referensi: CodecTypes['pg/int4@1']['output'] | null;
      readonly id_user: CodecTypes['pg/int4@1']['output'];
    };
    readonly Penagihan: {
      readonly id_penagihan: CodecTypes['pg/int4@1']['output'];
      readonly percobaan_ke: CodecTypes['pg/int4@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly nominal: CodecTypes['pg/int4@1']['output'] | null;
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly catatan: CodecTypes['pg/text@1']['output'] | null;
      readonly id_pesanan: CodecTypes['pg/int4@1']['output'];
      readonly id_penagih: CodecTypes['pg/int4@1']['output'];
    };
    readonly Pesanan: {
      readonly id_pesanan: CodecTypes['pg/int4@1']['output'];
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly qty: CodecTypes['pg/int4@1']['output'];
      readonly total_harga: CodecTypes['pg/int4@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly id_klien: CodecTypes['pg/int4@1']['output'];
      readonly id_barang: CodecTypes['pg/int4@1']['output'];
      readonly id_sales: CodecTypes['pg/int4@1']['output'];
      readonly id_nego: CodecTypes['pg/int4@1']['output'];
    };
    readonly Potongan: {
      readonly id_potongan: CodecTypes['pg/int4@1']['output'];
      readonly jenis: CodecTypes['pg/text@1']['output'];
      readonly nominal: CodecTypes['pg/int4@1']['output'];
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id_user: CodecTypes['pg/int4@1']['output'];
    };
    readonly User: {
      readonly id_user: CodecTypes['pg/int4@1']['output'];
      readonly nama: CodecTypes['pg/text@1']['output'];
      readonly username: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly role: 'ADMIN' | 'NEGO' | 'SALES' | 'PENAGIH';
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Barang: {
      readonly id_barang: CodecTypes['pg/int4@1']['input'];
      readonly nama_barang: CodecTypes['pg/text@1']['input'];
      readonly harga: CodecTypes['pg/int4@1']['input'];
      readonly harga_beli: CodecTypes['pg/int4@1']['input'];
      readonly komisi_penjualan: CodecTypes['pg/int4@1']['input'];
    };
    readonly Klien: {
      readonly id_klien: CodecTypes['pg/int4@1']['input'];
      readonly nama: CodecTypes['pg/text@1']['input'];
      readonly alamat: CodecTypes['pg/text@1']['input'] | null;
      readonly kontak: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly KomisiLog: {
      readonly id_log: CodecTypes['pg/int4@1']['input'];
      readonly jenis_komisi: CodecTypes['pg/text@1']['input'];
      readonly nominal_masuk: CodecTypes['pg/int4@1']['input'];
      readonly id_referensi: CodecTypes['pg/int4@1']['input'] | null;
      readonly id_user: CodecTypes['pg/int4@1']['input'];
    };
    readonly Penagihan: {
      readonly id_penagihan: CodecTypes['pg/int4@1']['input'];
      readonly percobaan_ke: CodecTypes['pg/int4@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly nominal: CodecTypes['pg/int4@1']['input'] | null;
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly catatan: CodecTypes['pg/text@1']['input'] | null;
      readonly id_pesanan: CodecTypes['pg/int4@1']['input'];
      readonly id_penagih: CodecTypes['pg/int4@1']['input'];
    };
    readonly Pesanan: {
      readonly id_pesanan: CodecTypes['pg/int4@1']['input'];
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly qty: CodecTypes['pg/int4@1']['input'];
      readonly total_harga: CodecTypes['pg/int4@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly id_klien: CodecTypes['pg/int4@1']['input'];
      readonly id_barang: CodecTypes['pg/int4@1']['input'];
      readonly id_sales: CodecTypes['pg/int4@1']['input'];
      readonly id_nego: CodecTypes['pg/int4@1']['input'];
    };
    readonly Potongan: {
      readonly id_potongan: CodecTypes['pg/int4@1']['input'];
      readonly jenis: CodecTypes['pg/text@1']['input'];
      readonly nominal: CodecTypes['pg/int4@1']['input'];
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id_user: CodecTypes['pg/int4@1']['input'];
    };
    readonly User: {
      readonly id_user: CodecTypes['pg/int4@1']['input'];
      readonly nama: CodecTypes['pg/text@1']['input'];
      readonly username: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly role: 'ADMIN' | 'NEGO' | 'SALES' | 'PENAGIH';
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly barang: {
      readonly harga: CodecTypes['pg/int4@1']['output'];
      readonly harga_beli: CodecTypes['pg/int4@1']['output'];
      readonly id_barang: CodecTypes['pg/int4@1']['output'];
      readonly komisi_penjualan: CodecTypes['pg/int4@1']['output'];
      readonly nama_barang: CodecTypes['pg/text@1']['output'];
    };
    readonly klien: {
      readonly alamat: CodecTypes['pg/text@1']['output'] | null;
      readonly id_klien: CodecTypes['pg/int4@1']['output'];
      readonly kontak: CodecTypes['pg/text@1']['output'] | null;
      readonly nama: CodecTypes['pg/text@1']['output'];
    };
    readonly komisiLog: {
      readonly id_log: CodecTypes['pg/int4@1']['output'];
      readonly id_referensi: CodecTypes['pg/int4@1']['output'] | null;
      readonly id_user: CodecTypes['pg/int4@1']['output'];
      readonly jenis_komisi: CodecTypes['pg/text@1']['output'];
      readonly nominal_masuk: CodecTypes['pg/int4@1']['output'];
    };
    readonly penagihan: {
      readonly catatan: CodecTypes['pg/text@1']['output'] | null;
      readonly id_penagih: CodecTypes['pg/int4@1']['output'];
      readonly id_penagihan: CodecTypes['pg/int4@1']['output'];
      readonly id_pesanan: CodecTypes['pg/int4@1']['output'];
      readonly nominal: CodecTypes['pg/int4@1']['output'] | null;
      readonly percobaan_ke: CodecTypes['pg/int4@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly pesanan: {
      readonly id_barang: CodecTypes['pg/int4@1']['output'];
      readonly id_klien: CodecTypes['pg/int4@1']['output'];
      readonly id_nego: CodecTypes['pg/int4@1']['output'];
      readonly id_pesanan: CodecTypes['pg/int4@1']['output'];
      readonly id_sales: CodecTypes['pg/int4@1']['output'];
      readonly qty: CodecTypes['pg/int4@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly total_harga: CodecTypes['pg/int4@1']['output'];
    };
    readonly potongan: {
      readonly id_potongan: CodecTypes['pg/int4@1']['output'];
      readonly id_user: CodecTypes['pg/int4@1']['output'];
      readonly jenis: CodecTypes['pg/text@1']['output'];
      readonly nominal: CodecTypes['pg/int4@1']['output'];
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly user: {
      readonly id_user: CodecTypes['pg/int4@1']['output'];
      readonly nama: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly role: 'ADMIN' | 'NEGO' | 'SALES' | 'PENAGIH';
      readonly username: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly barang: {
      readonly harga: CodecTypes['pg/int4@1']['input'];
      readonly harga_beli: CodecTypes['pg/int4@1']['input'];
      readonly id_barang: CodecTypes['pg/int4@1']['input'];
      readonly komisi_penjualan: CodecTypes['pg/int4@1']['input'];
      readonly nama_barang: CodecTypes['pg/text@1']['input'];
    };
    readonly klien: {
      readonly alamat: CodecTypes['pg/text@1']['input'] | null;
      readonly id_klien: CodecTypes['pg/int4@1']['input'];
      readonly kontak: CodecTypes['pg/text@1']['input'] | null;
      readonly nama: CodecTypes['pg/text@1']['input'];
    };
    readonly komisiLog: {
      readonly id_log: CodecTypes['pg/int4@1']['input'];
      readonly id_referensi: CodecTypes['pg/int4@1']['input'] | null;
      readonly id_user: CodecTypes['pg/int4@1']['input'];
      readonly jenis_komisi: CodecTypes['pg/text@1']['input'];
      readonly nominal_masuk: CodecTypes['pg/int4@1']['input'];
    };
    readonly penagihan: {
      readonly catatan: CodecTypes['pg/text@1']['input'] | null;
      readonly id_penagih: CodecTypes['pg/int4@1']['input'];
      readonly id_penagihan: CodecTypes['pg/int4@1']['input'];
      readonly id_pesanan: CodecTypes['pg/int4@1']['input'];
      readonly nominal: CodecTypes['pg/int4@1']['input'] | null;
      readonly percobaan_ke: CodecTypes['pg/int4@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly pesanan: {
      readonly id_barang: CodecTypes['pg/int4@1']['input'];
      readonly id_klien: CodecTypes['pg/int4@1']['input'];
      readonly id_nego: CodecTypes['pg/int4@1']['input'];
      readonly id_pesanan: CodecTypes['pg/int4@1']['input'];
      readonly id_sales: CodecTypes['pg/int4@1']['input'];
      readonly qty: CodecTypes['pg/int4@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly total_harga: CodecTypes['pg/int4@1']['input'];
    };
    readonly potongan: {
      readonly id_potongan: CodecTypes['pg/int4@1']['input'];
      readonly id_user: CodecTypes['pg/int4@1']['input'];
      readonly jenis: CodecTypes['pg/text@1']['input'];
      readonly nominal: CodecTypes['pg/int4@1']['input'];
      readonly tanggal: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly user: {
      readonly id_user: CodecTypes['pg/int4@1']['input'];
      readonly nama: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly role: 'ADMIN' | 'NEGO' | 'SALES' | 'PENAGIH';
      readonly username: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_User = {
    id_user: CodecTypes['pg/int4@1']['output'];
    nama: CodecTypes['pg/text@1']['output'];
    username: CodecTypes['pg/text@1']['output'];
    password: CodecTypes['pg/text@1']['output'];
    role: 'ADMIN' | 'NEGO' | 'SALES' | 'PENAGIH';
    komisiLog: public_KomisiLog[];
    penagihan: public_Penagihan[];
    pesananNego: public_Pesanan[];
    pesananSales: public_Pesanan[];
    potongan: public_Potongan[];
    readonly [RelationKeys]?:
      'komisiLog' | 'penagihan' | 'pesananNego' | 'pesananSales' | 'potongan';
  };
  export type public_Klien = {
    id_klien: CodecTypes['pg/int4@1']['output'];
    nama: CodecTypes['pg/text@1']['output'];
    alamat: CodecTypes['pg/text@1']['output'] | null;
    kontak: CodecTypes['pg/text@1']['output'] | null;
    pesanan: public_Pesanan[];
    readonly [RelationKeys]?: 'pesanan';
  };
  export type public_Barang = {
    id_barang: CodecTypes['pg/int4@1']['output'];
    nama_barang: CodecTypes['pg/text@1']['output'];
    harga: CodecTypes['pg/int4@1']['output'];
    harga_beli: CodecTypes['pg/int4@1']['output'];
    komisi_penjualan: CodecTypes['pg/int4@1']['output'];
    pesanan: public_Pesanan[];
    readonly [RelationKeys]?: 'pesanan';
  };
  export type public_Pesanan = {
    id_pesanan: CodecTypes['pg/int4@1']['output'];
    tanggal: CodecTypes['pg/timestamptz-temporal@1']['output'];
    qty: CodecTypes['pg/int4@1']['output'];
    total_harga: CodecTypes['pg/int4@1']['output'];
    status: CodecTypes['pg/text@1']['output'];
    id_klien: CodecTypes['pg/int4@1']['output'];
    id_barang: CodecTypes['pg/int4@1']['output'];
    id_sales: CodecTypes['pg/int4@1']['output'];
    id_nego: CodecTypes['pg/int4@1']['output'];
    barang: public_Barang;
    klien: public_Klien;
    nego: public_User;
    penagihan: public_Penagihan[];
    sales: public_User;
    readonly [RelationKeys]?: 'barang' | 'klien' | 'nego' | 'penagihan' | 'sales';
  };
  export type public_Penagihan = {
    id_penagihan: CodecTypes['pg/int4@1']['output'];
    percobaan_ke: CodecTypes['pg/int4@1']['output'];
    status: CodecTypes['pg/text@1']['output'];
    nominal: CodecTypes['pg/int4@1']['output'] | null;
    tanggal: CodecTypes['pg/timestamptz-temporal@1']['output'];
    catatan: CodecTypes['pg/text@1']['output'] | null;
    id_pesanan: CodecTypes['pg/int4@1']['output'];
    id_penagih: CodecTypes['pg/int4@1']['output'];
    penagih: public_User;
    pesanan: public_Pesanan;
    readonly [RelationKeys]?: 'penagih' | 'pesanan';
  };
  export type public_Potongan = {
    id_potongan: CodecTypes['pg/int4@1']['output'];
    jenis: CodecTypes['pg/text@1']['output'];
    nominal: CodecTypes['pg/int4@1']['output'];
    tanggal: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id_user: CodecTypes['pg/int4@1']['output'];
    user: public_User;
    readonly [RelationKeys]?: 'user';
  };
  export type public_KomisiLog = {
    id_log: CodecTypes['pg/int4@1']['output'];
    jenis_komisi: CodecTypes['pg/text@1']['output'];
    nominal_masuk: CodecTypes['pg/int4@1']['output'];
    id_referensi: CodecTypes['pg/int4@1']['output'] | null;
    id_user: CodecTypes['pg/int4@1']['output'];
    user: public_User;
    readonly [RelationKeys]?: 'user';
  };
}

export declare const models: {
  public: {
    User: Models.public_User;
    Klien: Models.public_Klien;
    Barang: Models.public_Barang;
    Pesanan: Models.public_Pesanan;
    Penagihan: Models.public_Penagihan;
    Potongan: Models.public_Potongan;
    KomisiLog: Models.public_KomisiLog;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly barang: {
              columns: {
                readonly id_barang: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nama_barang: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly harga: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly harga_beli: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly komisi_penjualan: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id_barang'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly klien: {
              columns: {
                readonly id_klien: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nama: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly alamat: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly kontak: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id_klien'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly komisiLog: {
              columns: {
                readonly id_log: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly jenis_komisi: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nominal_masuk: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id_referensi: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly id_user: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id_log'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'komisiLog_id_user_idx_52684e74';
                  readonly prefix: 'komisiLog_id_user_idx';
                  readonly columns: readonly ['id_user'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'komisiLog';
                    readonly columns: readonly ['id_user'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id_user'];
                  };
                },
              ];
            };
            readonly penagihan: {
              columns: {
                readonly id_penagihan: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly percobaan_ke: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nominal: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly tanggal: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly catatan: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id_pesanan: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id_penagih: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id_penagihan'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'penagihan_id_pesanan_idx_cba61da2';
                  readonly prefix: 'penagihan_id_pesanan_idx';
                  readonly columns: readonly ['id_pesanan'];
                  readonly unique: false;
                },
                {
                  readonly name: 'penagihan_id_penagih_idx_d0331a88';
                  readonly prefix: 'penagihan_id_penagih_idx';
                  readonly columns: readonly ['id_penagih'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'penagihan';
                    readonly columns: readonly ['id_pesanan'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pesanan';
                    readonly columns: readonly ['id_pesanan'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'penagihan';
                    readonly columns: readonly ['id_penagih'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id_user'];
                  };
                },
              ];
            };
            readonly pesanan: {
              columns: {
                readonly id_pesanan: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly tanggal: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly qty: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly total_harga: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id_klien: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id_barang: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id_sales: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id_nego: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id_pesanan'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'pesanan_id_klien_idx_a043e45c';
                  readonly prefix: 'pesanan_id_klien_idx';
                  readonly columns: readonly ['id_klien'];
                  readonly unique: false;
                },
                {
                  readonly name: 'pesanan_id_barang_idx_1a8610ff';
                  readonly prefix: 'pesanan_id_barang_idx';
                  readonly columns: readonly ['id_barang'];
                  readonly unique: false;
                },
                {
                  readonly name: 'pesanan_id_sales_idx_2e8e4f57';
                  readonly prefix: 'pesanan_id_sales_idx';
                  readonly columns: readonly ['id_sales'];
                  readonly unique: false;
                },
                {
                  readonly name: 'pesanan_id_nego_idx_66b843d2';
                  readonly prefix: 'pesanan_id_nego_idx';
                  readonly columns: readonly ['id_nego'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pesanan';
                    readonly columns: readonly ['id_klien'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'klien';
                    readonly columns: readonly ['id_klien'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pesanan';
                    readonly columns: readonly ['id_barang'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'barang';
                    readonly columns: readonly ['id_barang'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pesanan';
                    readonly columns: readonly ['id_sales'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id_user'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pesanan';
                    readonly columns: readonly ['id_nego'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id_user'];
                  };
                },
              ];
            };
            readonly potongan: {
              columns: {
                readonly id_potongan: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly jenis: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nominal: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly tanggal: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id_user: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id_potongan'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'potongan_id_user_idx_52684e74';
                  readonly prefix: 'potongan_id_user_idx';
                  readonly columns: readonly ['id_user'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'potongan';
                    readonly columns: readonly ['id_user'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id_user'];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id_user: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nama: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly username: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'SALES'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id_user'] };
              uniques: readonly [{ readonly columns: readonly ['username'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly Role: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ADMIN', 'NEGO', 'SALES', 'PENAGIH'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly klien: { readonly namespace: 'public' & NamespaceId; readonly model: 'Klien' };
    readonly barang: { readonly namespace: 'public' & NamespaceId; readonly model: 'Barang' };
    readonly pesanan: { readonly namespace: 'public' & NamespaceId; readonly model: 'Pesanan' };
    readonly penagihan: { readonly namespace: 'public' & NamespaceId; readonly model: 'Penagihan' };
    readonly potongan: { readonly namespace: 'public' & NamespaceId; readonly model: 'Potongan' };
    readonly komisiLog: { readonly namespace: 'public' & NamespaceId; readonly model: 'KomisiLog' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Barang: {
            readonly fields: {
              readonly id_barang: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nama_barang: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly harga: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly harga_beli: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly komisi_penjualan: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly pesanan: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pesanan';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id_barang'];
                  readonly targetFields: readonly ['id_barang'];
                };
              };
            };
            readonly storage: {
              readonly table: 'barang';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id_barang: { readonly column: 'id_barang' };
                readonly nama_barang: { readonly column: 'nama_barang' };
                readonly harga: { readonly column: 'harga' };
                readonly harga_beli: { readonly column: 'harga_beli' };
                readonly komisi_penjualan: { readonly column: 'komisi_penjualan' };
              };
            };
          };
          readonly Klien: {
            readonly fields: {
              readonly id_klien: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nama: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly alamat: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly kontak: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly pesanan: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pesanan';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id_klien'];
                  readonly targetFields: readonly ['id_klien'];
                };
              };
            };
            readonly storage: {
              readonly table: 'klien';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id_klien: { readonly column: 'id_klien' };
                readonly nama: { readonly column: 'nama' };
                readonly alamat: { readonly column: 'alamat' };
                readonly kontak: { readonly column: 'kontak' };
              };
            };
          };
          readonly KomisiLog: {
            readonly fields: {
              readonly id_log: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly jenis_komisi: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nominal_masuk: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_referensi: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_user: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['id_user'];
                  readonly targetFields: readonly ['id_user'];
                };
              };
            };
            readonly storage: {
              readonly table: 'komisiLog';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id_log: { readonly column: 'id_log' };
                readonly jenis_komisi: { readonly column: 'jenis_komisi' };
                readonly nominal_masuk: { readonly column: 'nominal_masuk' };
                readonly id_referensi: { readonly column: 'id_referensi' };
                readonly id_user: { readonly column: 'id_user' };
              };
            };
          };
          readonly Penagihan: {
            readonly fields: {
              readonly id_penagihan: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly percobaan_ke: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nominal: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tanggal: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly catatan: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id_pesanan: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_penagih: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly penagih: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['id_penagih'];
                  readonly targetFields: readonly ['id_user'];
                };
              };
              readonly pesanan: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pesanan';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['id_pesanan'];
                  readonly targetFields: readonly ['id_pesanan'];
                };
              };
            };
            readonly storage: {
              readonly table: 'penagihan';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id_penagihan: { readonly column: 'id_penagihan' };
                readonly percobaan_ke: { readonly column: 'percobaan_ke' };
                readonly status: { readonly column: 'status' };
                readonly nominal: { readonly column: 'nominal' };
                readonly tanggal: { readonly column: 'tanggal' };
                readonly catatan: { readonly column: 'catatan' };
                readonly id_pesanan: { readonly column: 'id_pesanan' };
                readonly id_penagih: { readonly column: 'id_penagih' };
              };
            };
          };
          readonly Pesanan: {
            readonly fields: {
              readonly id_pesanan: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tanggal: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly qty: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly total_harga: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id_klien: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_barang: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_sales: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id_nego: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly barang: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Barang';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['id_barang'];
                  readonly targetFields: readonly ['id_barang'];
                };
              };
              readonly klien: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Klien';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['id_klien'];
                  readonly targetFields: readonly ['id_klien'];
                };
              };
              readonly nego: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['id_nego'];
                  readonly targetFields: readonly ['id_user'];
                };
              };
              readonly penagihan: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Penagihan';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id_pesanan'];
                  readonly targetFields: readonly ['id_pesanan'];
                };
              };
              readonly sales: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['id_sales'];
                  readonly targetFields: readonly ['id_user'];
                };
              };
            };
            readonly storage: {
              readonly table: 'pesanan';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id_pesanan: { readonly column: 'id_pesanan' };
                readonly tanggal: { readonly column: 'tanggal' };
                readonly qty: { readonly column: 'qty' };
                readonly total_harga: { readonly column: 'total_harga' };
                readonly status: { readonly column: 'status' };
                readonly id_klien: { readonly column: 'id_klien' };
                readonly id_barang: { readonly column: 'id_barang' };
                readonly id_sales: { readonly column: 'id_sales' };
                readonly id_nego: { readonly column: 'id_nego' };
              };
            };
          };
          readonly Potongan: {
            readonly fields: {
              readonly id_potongan: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly jenis: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nominal: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tanggal: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id_user: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['id_user'];
                  readonly targetFields: readonly ['id_user'];
                };
              };
            };
            readonly storage: {
              readonly table: 'potongan';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id_potongan: { readonly column: 'id_potongan' };
                readonly jenis: { readonly column: 'jenis' };
                readonly nominal: { readonly column: 'nominal' };
                readonly tanggal: { readonly column: 'tanggal' };
                readonly id_user: { readonly column: 'id_user' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id_user: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nama: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly username: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly komisiLog: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'KomisiLog';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id_user'];
                  readonly targetFields: readonly ['id_user'];
                };
              };
              readonly penagihan: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Penagihan';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id_user'];
                  readonly targetFields: readonly ['id_penagih'];
                };
              };
              readonly pesananNego: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pesanan';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id_user'];
                  readonly targetFields: readonly ['id_nego'];
                };
              };
              readonly pesananSales: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pesanan';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id_user'];
                  readonly targetFields: readonly ['id_sales'];
                };
              };
              readonly potongan: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Potongan';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id_user'];
                  readonly targetFields: readonly ['id_user'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id_user: { readonly column: 'id_user' };
                readonly nama: { readonly column: 'nama' };
                readonly username: { readonly column: 'username' };
                readonly password: { readonly column: 'password' };
                readonly role: { readonly column: 'role' };
              };
            };
          };
        };
        readonly enum: {
          readonly Role: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ADMIN'; readonly value: 'ADMIN' },
              { readonly name: 'NEGO'; readonly value: 'NEGO' },
              { readonly name: 'SALES'; readonly value: 'SALES' },
              { readonly name: 'PENAGIH'; readonly value: 'PENAGIH' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
